# Generated by Django 4.1.3 on 2022-11-02 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('item_state', models.CharField(choices=[('new', 'new'), ('refurb', 'refurb')], default='new', max_length=32)),
                ('item_image', models.ImageField(upload_to='images')),
                ('item_tag', models.CharField(choices=[('hp', 'hp'), ('samsung', 'samsung'), ('apple', 'apple'), ('dell', 'dell'), ('lenovo', 'lenovo'), ('accessory', 'accessory')], default='hp', max_length=32)),
                ('item_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_cat', to='inventory.category')),
            ],
        ),
    ]
